### ISSUE TITLE
Linux packaging export problem

### ISSUE THREAD

**Issue by xlinbsd** [Unforgiven-wanda/electrify-updated-test#3]
Hi,

Sorry to disturb but I found out another packaging problem on
```
Linux 4.4.0-47 (ubuntu 16.04.1)
Meteor 1.4.2.3
electrify 2.2.0
```

The packaging process seems go wrong on the last mv staging, since the output dir is deleted and nothing is replacing it, the bundle in /tmp/electrify/package is incomplete, the app/app dir does not exist to start. The .dist dir is not created either.

The error when packaging, with or without -o option, last lines :

```
Packaging app for platform linux x64 using electron v1.4.8
mv: omitting directory '/tmp/electrify/package'
mv: path is a directory

```

**Comment by HZSamir** [comment]
Does this issue also occur when using the original Electrify?
Try removing `electrify-updated-test` and installing `electrify` and please let me know.

**Comment by xlinbsd** [comment]
With electrify, I have a cousin error : "EXDEV: cross-device link not permitted…"

So I tried on another Linux box with /tmp and /home on the same partition, the error does not occur.

The error seems to be in the last step when moving from /tmp to the .dist or "-o dir" and can not resolve paths on other partition or disk. Can you help on this ? What are the commands used, perhaps I can help you for "bashing" that ?

**Comment by HZSamir** [comment]
I must admit I am stumped, as I've never encountered this problem myself. Though I seem to remember there was someone with the same issue who reported it on Electrify's Gitter, but I can't remember for the life of me how. You could check there.

Sorry I can't be of much help here.

**Comment by xlinbsd** [comment]
I will search a bit before closing, in case I can bring you a clue to update something.

**Comment by xlinbsd** [comment]
I perhaps found out the original problem here and a potential solution given for electrify.

[electrify issue 35](https://github.com/arboleya/electrify/issues/35)

Can an update be done on your coding ?

**Comment by xlinbsd** [comment]
I had to reformat my main machine, I choose a unified / partition, so I do not have the problem anymore, but the bug persist. Anyway, since I know how to circumvent it, I close the ticket.
