### ISSUE TITLE
[feature] package with open http

### ISSUE THREAD

**Issue by xlinbsd** [Unforgiven-wanda/electrify-updated-test#5]
Hello,

Do you know if it is possible to package an app with the http://localhost:3000 still opened like the `electrify` command does work ?

**Comment by HZSamir** [comment]
I'm sorry? You mean accessing http://localhost:3000 in the browser while the app is running, perhaps?

**Comment by xlinbsd** [comment]
yep

**Comment by HZSamir** [comment]
Ah, then no, sorry. I remember trying something along those lines, but I didn't get far, so I dropped it.
I'll try to look it up in the code, perhaps I'll find some lead for you.

**Comment by HZSamir** [comment]
Nope. Looked at it, still no idea how to do that, sorry :/

**Comment by xlinbsd** [comment]
Thank you.
