### ISSUE TITLE
Can not open the app from package

### ISSUE THREAD

**Issue by iaroshvictor** [Unforgiven-wanda/electrify-updated-test#6]
Hy, i'm trying to build a meteor app form windows 7 x64.
The steps 've done:
-meteor create app name
-cd appname
-npm install -g electrify-updated-test
-electrify 
(at this step all works perfectly, a window is oppened)
-electrify package 
open the .electrify/.dist/my-electrified-app-win32-x64, try to run my-electrified-app.exe and absolutely nothink happens. 
I can see in the task manager the process, but no window of my app appears.

**Comment by HZSamir** [comment]
Try running the .exe from the cmd, there might be some helpful log.
(I suspect something with Mongodb, it usually him the culprit)

**Comment by iaroshvictor** [comment]
![cap](https://cloud.githubusercontent.com/assets/25705590/24193412/d7907d6e-0efa-11e7-835b-2e4352503363.PNG)

**Comment by HZSamir** [comment]
Yep, this is exactly what I suspected, see this https://github.com/Unforgiven-wanda/electrify-updated-test#how-to-fix and more particularly this issue to fix it https://github.com/arboleya/electrify/issues/61#issuecomment-238031131

And just as a tip, I see you're trying to run this on a x86 machine, MongoDB has a severe limitation of 2gb of data on this kind of hardware (you can see it written in your log), my advice is to use something else, like CouchDB with is every bit as good, without the minus of storage limit.

Good luck to you, let me know if it is fixed :)

**Comment by iaroshvictor** [comment]
I tried to copy Mongo and Mongod from 3.2.6 version to myapp/resources/app/bin
Then run the exe of my app, and it is stuck at electrify:plugins:mongodb: staring mongo...

**Comment by HZSamir** [comment]
Have you packaged again? Remove the package app and run `electrify package` again

**Comment by iaroshvictor** [comment]
Worked Perfectly

**Comment by iaroshvictor** [comment]
still stuck at starting mongo

**Comment by iaroshvictor** [comment]
It worked with 3.2.12version of Mongo
